### ISSUE TITLE
don't rely on settings in src

### ISSUE THREAD

**Issue by pYr0x** [asadijabar/push-notification-library#1]
to edit the vendor src is not a good solution. on very update, the settings will be overwritten.
provide an interface for settings and inject the settings class into the main class.

**Comment by Azhovan** [comment]
Good suggestion,  feel free to make a pull request about it or i will update the code

**Comment by Azhovan** [comment]
added

**Comment by pYr0x** [comment]
i think this PR does't make it better... :/
pls provide dependency injection. http://php-di.org/
do not rely on any changes inside the `vendor` folder.

**Comment by Azhovan** [comment]
i will update that at next version
