### ISSUE TITLE
Invalid syntax in .env File

### ISSUE THREAD

**Issue by marslanniaz** [asadijabar/push-notification-library#2]
The syntax of .env file at https://github.com/asadijabar/push-notification-library/blob/master/.env.example in invalid. 
It should be like 

APNS_CERTIFICATION_FILE_PATH=file.pem
APNS_URL=ssl://gateway.push.apple.com:2195
FCM_API_ACCESS_KEY=
FCM_URL=https://fcm.googleapis.com/fcm/send
GOOGLE_CONTENT_TYPE=application/json
Socket_Time_To_Live=60

no  " ' " or " ; "

**Comment by Azhovan** [comment]
fixed

**Comment by marslanniaz** [comment]
Great and Thanks your code is really helpful.
