### ISSUE TITLE
Regular expression for preg_match() should be updated

### ISSUE THREAD

**Issue by marslanniaz** [asadijabar/push-notification-library#3]
The preg_match() at [line] (https://github.com/asadijabar/push-notification-library/blob/master/src/PushNotification/Device/Strategy/AppleIOS.php#L84) 

Should be updated. 
if (preg_match('/[^0-9a-fA-F]/', $token)) {
}

In current status if you pass all capital string of device token it returns **Invalid device token error**.
With this change it will support for All CAPITAL string of device token as well.

**Comment by Azhovan** [comment]
since this way of checking is not efficient, I will remove those lines of code in next update

**Comment by marslanniaz** [comment]
OK.
