### ISSUE TITLE
Got problem when sending too many push notifications

### ISSUE THREAD

**Issue by dongmai** [asadijabar/push-notification-library#6]
Sometimes it got crash at `class_exists` function from `/push-notification/push-notification-php-library/src/PushNotification/Message/Factory/MessageFactory.php` file and I dont know how to resolve it.

Any suggestion for this, thanks!

**Comment by Azhovan** [comment]
please put all the exception message here

**Comment by dongmai** [comment]
no exception was thrown, it just stopped at `class_exists` function.

**Comment by dongmai** [comment]
Hi, I've found what exactly the reason is. It will got problem if I'm trying to send push notification for a list of devices that contains both ios and android devices.

For example I have a list of devices as [iOS, iOS, Android], when loop through this array and send push for each device, first two devices will receive the notification but the last one won't.

And as debugging I see the program will stop at `class_exists` function as above.

I've tried to create separated instances of PushService per platform (ios, android) but no luck.

**Comment by dongmai** [comment]
@asadijabar Do you have any suggestion on resolving this?  :)

**Comment by Azhovan** [comment]
@dongmai 
the code :
`if (!class_exists(MessageConfig::MESSAGE_NAMESPACE . $this->message)) {
            throw new PushException('class does not exist :' . MessageConfig::MESSAGE_NAMESPACE . $this->message);
        }`

that exception happened when you are going to create messages that cannot be mapped to implemented  strategies. currently there are two strategies `AndroidMessages` and `IOSMessages` . please make sure you are using correct names.
